apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-service
spec:
  template:
    spec:
      containers:
      - image: europe-west4-docker.pkg.dev/reuniquiz/prod/app:prod
        ports:
        - name: http1
          containerPort: 8000
        # env:
        # - name: TELEGRAM_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       key: latest
        #       name: TELEGRAM_TOKEN